### ISSUE TITLE
specifycolor: basic preference api char limit

### ISSUE THREAD

**Issue by diodewaal** [Socialery/HexChatScripts#3]
Hi, first of all: thanks for making this addon.

I came across a problem, when I /setcolor'ed yet another nick. The preference line would eventually become too long (> 512 characters), Hexchat would crash and not be able to load the plugin again and throw out a json error. (See the following gist for example log and conf file. https://gist.github.com/diodewaal/ef73cd168244b190ce71 )

I discussed this in the official #hexchat channel, and TingPing suggested to make one setting per nick color. (He added the following example https://github.com/TingPing/plugins/blob/master/HexChat/alias.py#L16 )

**Comment by Socialery** [comment]
My past decisions are catching up to me!

The suggestion sounds fairly unmaintainable, which is good enough for me, I'll start work on it

**Comment by Socialery** [comment]
That should probably work, who knows, probably doesn't! I can't even read my own code!

I'll message you a list of commands to recreate your pre-existing settings

**Comment by diodewaal** [comment]
Woah, great job! I'm happy you could figure it out fairly quickly!

**Comment by Socialery** [comment]
I ended up emailing the commands, since apparently github doesn't have messages.

And yeah, only just checked in with github ~1h ago, I really should use notifications more!

**Comment by diodewaal** [comment]
It totally works! Thanks again!


On Tue, Mar 3, 2015 at 7:06 AM, Socialery <notifications@github.com> wrote:

> I ended up emailing the commands, since apparently github doesn't have
> messages.
>
> And yeah, only just checked in with github ~1h ago, I really should use
> notifications more!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Socialery/HexChatScripts/issues/3#issuecomment-76892373>
> .
>



-- 
Dana de Waal
